package com.programmerare.crsTransformations.crsIdentifier

/**
 * An instance of this class is representing a coordinate reference system 
 * defined by its so called EPSG code.
 * Instances are created from factory methods with an EPSG code as the parameter.
 * When using Java, the factory methods are available in a class named 'CrsIdentifierFactory'.
 * When using Kotlin, the factory methods are available as package level functions.
 * 
 * CRS = Coordinate Reference System (a.k.a. SRS = Spatial Reference System)  
 * 
 * https://en.wikipedia.org/wiki/Spatial_reference_system
 *
 * EPSG = European Petroleum Survey Group.  
 * 
 * EPSG was a scientific organization which created a widely used database
 * of Earth ellipsoids, geodetic datums, geographic and projected coordinate systems,
 * units of measurement, etc.  
 * 
 * https://en.wikipedia.org/wiki/International_Association_of_Oil_%26_Gas_Producers  
 * 
 * http://www.epsg-registry.org  
 * 
 * http://www.epsg.org  
 * 
 * http://epsg.io/  
 */
class CrsIdentifier private constructor(

    /**
     * a code representing a coordinate reference system, 
     * which should be a string beginning with "EPSG:" and 
     * then an EPSG number such as '4326' i.e. the return string 
     * should be something like "EPSG:4326" 
     */
    val crsCode: String,

    /**
     * @return true if the instance represents an EPSG code and false otherwise.
     * 
     * Normally the method should always be true since EPSG code are expected 
     * by the transform methods, and if this method would return false then 
     * there was some problem at the construction of the instance, e.g. 
     * trying to create the instance with a string not beginning with "EPSG:"
     */
    val isEpsgCode: Boolean,

    /**
     * @return an EPSG number, for example 4326 for the frequently used coordinate reference system WGS84.
     */
    val epsgNumber: Int
) {

    //------------------------------------------------------------------
    // The implementation of the following three methods were generated by IntelliJ IDEA

    /**
     * Implementation generated by IntelliJ IDEA. 
     */
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as CrsIdentifier

        if (crsCode != other.crsCode) return false
        if (isEpsgCode != other.isEpsgCode) return false
        if (epsgNumber != other.epsgNumber) return false

        return true
    }

    /**
     * Implementation generated by IntelliJ IDEA.
     */    
    override fun hashCode(): Int {
        var result = crsCode.hashCode()
        result = 31 * result + isEpsgCode.hashCode()
        result = 31 * result + epsgNumber
        return result
    }

    /**
     * Implementation generated by IntelliJ IDEA.
     */    
    override fun toString(): String {
        return "CrsIdentifier(crsCode='$crsCode', isEpsgCode=$isEpsgCode, epsgNumber=$epsgNumber)"
    }
    //------------------------------------------------------------------

    internal companion object {
        /**
         * Kotlin factory method with access level "internal".
         * NOT indended for public use.
         * Please instead use the Java factory class CrsIdentifierFactory
         * or the package level factory methods in the crsIdentifier package.
         */
        @JvmStatic
        internal fun _internalCrsFactory(
            crsCode: String,
            isEpsgCode: Boolean,
            epsgNumber: Int
        ): CrsIdentifier {
            return CrsIdentifier( // private constructor
                crsCode,
                isEpsgCode,
                epsgNumber
            )
        }
    }
}