package com.programmerare.crsTransformations;

import com.programmerare.crsConstants.constantsByNumberNameArea.v9_5_4.EpsgNumber;
import com.programmerare.crsConstants.constantsByNumberNameArea.v9_5_4.EpsgCode;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

class CoordinateTest {
    private final double deltaTolerance = 0.00001;
    private final double xLongitude = 12.34;
    private final double yLatitude = 56.67;
    private final int epsgNumber = EpsgNumber._3006__SWEREF99_TM__SWEDEN;
    private final String epsgCode = EpsgCode._3006__SWEREF99_TM__SWEDEN;

    @Test
    void trivialCreateCoordinateTest() {
        Coordinate coordinate = CoordinateFactory.createFromXLongitudeYLatitude(xLongitude, yLatitude, epsgNumber);
        assertEquals(xLongitude, coordinate.getXLongitude(), deltaTolerance);
        assertEquals(yLatitude, coordinate.getYLatitude(), deltaTolerance);
        assertEquals(epsgNumber, coordinate.getCrsIdentifier().getEpsgNumber());
    }

    @Test
    void createCoordinatesWithEpsgNumberButWithDifferentOrderOfLatLongParameters() {
        Coordinate coordinate1 = CoordinateFactory.createFromXLongitudeYLatitude(xLongitude, yLatitude, epsgNumber);
        Coordinate coordinate2 = CoordinateFactory.createFromYLatitudeXLongitude(yLatitude, xLongitude, epsgNumber);
        assertEqualCoordinates(coordinate1, coordinate2);

        //CoordinateFactory.kallemetoden()
    }

    @Test
    void createCoordinatesWithCrsCodeButWithDifferentOrderOfLatLongParameters() {
        String crsCode = "EPSG:3006";
        Coordinate coordinate1 = CoordinateFactory.createFromXLongitudeYLatitude(xLongitude, yLatitude, crsCode);
        Coordinate coordinate2 = CoordinateFactory.createFromYLatitudeXLongitude(yLatitude, xLongitude, crsCode);
        assertEqualCoordinates(coordinate1, coordinate2);
    }

    @Test
    void createCoordinatesWithCrsIdentifierButWithDifferentOrderOfLatLongParameters() {
        CrsIdentifier crsIdentifier = CrsIdentifier.createFromEpsgNumber(3006);
        Coordinate coordinate1 = CoordinateFactory.createFromXLongitudeYLatitude(xLongitude, yLatitude, crsIdentifier);
        Coordinate coordinate2 = CoordinateFactory.createFromYLatitudeXLongitude(yLatitude, xLongitude, crsIdentifier);
        assertEqualCoordinates(coordinate1, coordinate2);
    }

    @Test
    void createCoordinatesWithWgs84AsDefaultWhenNotSpecifyingCRS() {
        double wgs84Lat = 59.330231;
        double wgs84Lon = 18.059196;

        Coordinate wgs84_1 = CoordinateFactory.createFromLongitudeLatitude(wgs84Lon, wgs84Lat);
        assertEquals(EpsgNumber._4326__WGS_84__WORLD, wgs84_1.getCrsIdentifier().getEpsgNumber());
        assertEquals(  EpsgCode._4326__WGS_84__WORLD, wgs84_1.getCrsIdentifier().getCrsCode());

        Coordinate wgs84_2 = CoordinateFactory.createFromLatitudeLongitude(wgs84Lat, wgs84Lon);
        assertEquals(EpsgNumber._4326__WGS_84__WORLD, wgs84_2.getCrsIdentifier().getEpsgNumber());
        assertEquals(  EpsgCode._4326__WGS_84__WORLD, wgs84_2.getCrsIdentifier().getCrsCode());

        Coordinate wgs84_3 = CoordinateFactory.createFromYLatitudeXLongitude(wgs84Lat, wgs84Lon, EpsgNumber._4326__WGS_84__WORLD);
        assertEqualCoordinates(wgs84_3, wgs84_1);
        assertEqualCoordinates(wgs84_3, wgs84_2);
    }

    private void assertEqualCoordinates(Coordinate coordinate1, Coordinate coordinate2) {
        assertEquals(coordinate1.getXLongitude(), coordinate2.getXLongitude(), deltaTolerance);
        assertEquals(coordinate1.getYLatitude(), coordinate2.getYLatitude(), deltaTolerance);
        assertEquals(coordinate1.getCrsIdentifier(), coordinate2.getCrsIdentifier()); // data class
        assertEquals(coordinate1.getCrsIdentifier().getEpsgNumber(), coordinate2.getCrsIdentifier().getEpsgNumber());

        // TODO: find out how the autogenerated implementations of equals and hashCode
        // are implemented in a Kotlin data class, e.g. Coordinate,
        // when properties are typed as double.
        // Maybe using Double.compare and Double.doubleToLongBits and following recommendations
        // of "Effective Java" book (Joshua Bloch)
        assertEquals(coordinate1.hashCode(), coordinate2.hashCode());
        assertEquals(coordinate1, coordinate2);
        // Note that the above assertion is not reliable since double fields are used.
        // Example below from an assertion failure in class CrsTransformationAdapterAverageTest:
        // assertEquals(coordinateWithAverageLatitudeAndLongitude, coordinateReturnedByCompositeAdapter);
        // Expected :Coordinate(xLongitude=674032.3572074446, yLatitude=6580821.991903967, crsIdentifier=CrsIdentifier(crsCode=EPSG:3006, isEpsgCode=true, epsgNumber=3006))
        // Actual   :Coordinate(xLongitude=674032.3572074447, yLatitude=6580821.991903967, crsIdentifier=CrsIdentifier(crsCode=EPSG:3006, isEpsgCode=true, epsgNumber=3006))
    }


    // The Coordinate class (implemented with Kotlin) does not explicitly implement
    // the methods equals and hashCode but the class is a "data class" (with an implicit/automatic implementation )
    @Test
    void assertEqualsAndHashCodeWhenSixDecimalsAreUsed() {
        Coordinate c1 = CoordinateFactory.createFromLatitudeLongitude(59.123456, 18.123456000);
        Coordinate c2 = CoordinateFactory.createFromLatitudeLongitude(59.123456000, 18.123456);
        assertEquals(
            c1, c2
        );
        assertEquals(
            c1.hashCode(), c2.hashCode()
        );
    }

    @Test
    void assertEqualsAndHashCodeWhenNineDecimalsAreUsed() {
        Coordinate c1 = CoordinateFactory.createFromLatitudeLongitude(59.123456789, 18.123456789000);
        Coordinate c2 = CoordinateFactory.createFromLatitudeLongitude(59.123456789000, 18.123456789);
        assertEquals(
            c1, c2
        );
        assertEquals(
            c1.hashCode(), c2.hashCode()
        );
    }

    @Test
    void assertNotEqualsWhenVerySmallDifference() {
        // very small latitude difference:
        assertNotEquals(
            CoordinateFactory.createFromLatitudeLongitude(59.123456789000, 18.123456789),
            CoordinateFactory.createFromLatitudeLongitude(59.123456789001, 18.123456789)
        );

        // very small longitude difference:
        assertNotEquals(
            CoordinateFactory.createFromLatitudeLongitude(59.123456789, 18.123456789000),
            CoordinateFactory.createFromLatitudeLongitude(59.123456789, 18.123456789001)
        );
    }


    @Test
    void assertEqualsWhenUsingEquivalentXYmethods() {
        Coordinate c1, c2, c3, c4, c5, c6, c7, c8, c9;

        // the last parameter is an integer for these three:
        c1 = CoordinateFactory.createFromXLongitudeYLatitude(xLongitude, yLatitude, epsgNumber);
        c2 = CoordinateFactory.lonLat(xLongitude, yLatitude, epsgNumber);
        c3 = CoordinateFactory.xy(xLongitude, yLatitude, epsgNumber);

        // the last parameter is s string for these three:
        c4 = CoordinateFactory.createFromXLongitudeYLatitude(xLongitude, yLatitude, epsgCode);
        c5 = CoordinateFactory.lonLat(xLongitude, yLatitude, epsgCode);
        c6 = CoordinateFactory.xy(xLongitude, yLatitude, epsgCode);

        CrsIdentifier crsIdentifier = CrsIdentifier.createFromEpsgNumber(epsgNumber);
        c7 = CoordinateFactory.createFromXLongitudeYLatitude(xLongitude, yLatitude, crsIdentifier);
        c8 = CoordinateFactory.lonLat(xLongitude, yLatitude, crsIdentifier);
        c9 = CoordinateFactory.xy(xLongitude, yLatitude, crsIdentifier);

        assertEquals(c1, c2);
        assertEquals(c1, c3);
        assertEquals(c1, c4);
        assertEquals(c1, c5);
        assertEquals(c1, c6);
        assertEquals(c1, c7);
        assertEquals(c1, c8);
        assertEquals(c1, c9);
    }

    @Test
    void assertEqualsWhenUsingEquivalentYXmethods() {
        Coordinate c1, c2, c3, c4, c5, c6, c7, c8, c9;

        // the last parameter is an integer for these three:
        c1 = CoordinateFactory.createFromYLatitudeXLongitude(yLatitude, xLongitude, epsgNumber);
        c2 = CoordinateFactory.latLon(yLatitude, xLongitude, epsgNumber);
        c3 = CoordinateFactory.yx(yLatitude, xLongitude, epsgNumber);

        // the last parameter is s string for these three:
        c4 = CoordinateFactory.createFromYLatitudeXLongitude(yLatitude, xLongitude, epsgCode);
        c5 = CoordinateFactory.latLon(yLatitude, xLongitude, epsgCode);
        c6 = CoordinateFactory.yx(yLatitude, xLongitude, epsgCode);

        CrsIdentifier crsIdentifier = CrsIdentifier.createFromEpsgNumber(epsgNumber);
        c7 = CoordinateFactory.createFromYLatitudeXLongitude(yLatitude, xLongitude, crsIdentifier);
        c8 = CoordinateFactory.latLon(yLatitude, xLongitude, crsIdentifier);
        c9 = CoordinateFactory.yx(yLatitude, xLongitude, crsIdentifier);

        assertEquals(c1, c2);
        assertEquals(c1, c3);
        assertEquals(c1, c4);
        assertEquals(c1, c5);
        assertEquals(c1, c6);
        assertEquals(c1, c7);
        assertEquals(c1, c8);
        assertEquals(c1, c9);
    }
}