package com.programmerare.crsTransformations

/**
 * CRS = Coordinate Reference System (a.k.a. SRS = Spatial Reference System)
 * https://en.wikipedia.org/wiki/Spatial_reference_system
 *
 * EPSG = European Petroleum Survey Group.
 * EPSG was a scientific organization which created a widely used database
 * of Earth ellipsoids, geodetic datums, geographic and projected coordinate systems,
 * units of measurement, etc.
 * https://en.wikipedia.org/wiki/International_Association_of_Oil_%26_Gas_Producers
 * http://www.epsg-registry.org
 * http://www.epsg.org
 * http://epsg.io/
 */
class CrsIdentifier internal constructor(
    val crsCode: String,
    val isEpsgCode: Boolean,
    val epsgNumber: Int
) {

    //------------------------------------------------------------------
    // The implementation of the following three methods were generated by IntelliJ IDEA
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as CrsIdentifier

        if (crsCode != other.crsCode) return false
        if (isEpsgCode != other.isEpsgCode) return false
        if (epsgNumber != other.epsgNumber) return false

        return true
    }

    override fun hashCode(): Int {
        var result = crsCode.hashCode()
        result = 31 * result + isEpsgCode.hashCode()
        result = 31 * result + epsgNumber
        return result
    }

    override fun toString(): String {
        return "CrsIdentifier(crsCode='$crsCode', isEpsgCode=$isEpsgCode, epsgNumber=$epsgNumber)"
    }
    //------------------------------------------------------------------
}